[tool.poetry]
name = "tap-getpocket"
version = "0.0.1"
description = "`tap-getpocket` is a Singer tap for Pocket, built with the Meltano SDK for Singer Taps."
authors = ["Edgar Ramírez-Mondragón <edgarrm358@gmail.com>"]
keywords = [
    "ELT",
    "Pocket",
    "getpocket",
]
license = "Apache 2.0"
readme = "README.md"
homepage = "https://github.com/edgarrmondragon/tap-getpocket"
repository = "https://github.com/edgarrmondragon/tap-getpocket"
documentation = "https://github.com/edgarrmondragon/tap-getpocket#readme"

[tool.poetry.dependencies]
python = "<3.11,>=3.7.1"
singer-sdk = "==0.13.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
mypy = "^0.982"
types-requests = "^2.28.10"

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
src_paths = "tap_getpocket"

[tool.pytest.ini_options]
addopts = "-vvv"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-getpocket = 'tap_getpocket.tap:TapPocket.cli'
