[tool.poetry]
name = "tap-pocket"
version = "0.0.1"
description = "`tap-pocket` is a Singer tap for Pocket, built with the Meltano SDK for Singer Taps."
authors = ["Edgar Ramírez-Mondragón"]
keywords = [
    "ELT",
    "Pocket",
]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "<3.11,>=3.6.2"
singer-sdk = "==0.3.17"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
tox = "^3.24.4"
black = "^21.9b0"
mypy = "^0.910"
types-requests = "^2.26.1"
isort = "^5.10.1"

# Flake8
flake8 = "^3.9.2"
flake8-docstrings = "^1.6.0"
flake8-annotations = "^2.7.0"
darglint = "^1.8.1"

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
src_paths = "tap_pocket"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-pocket = 'tap_pocket.tap:TapPocket.cli'
