[tool.poetry]
name = "tap-pocket"
version = "0.0.1"
description = "`tap-pocket` is a Singer tap for Pocket, built with the Meltano SDK for Singer Taps."
authors = ["Edgar Ramírez-Mondragón <edgarrm358@gmail.com>"]
keywords = [
    "ELT",
    "Pocket",
]
license = "Apache 2.0"
readme = "README.md"
homepage = "https://github.com/edgarrmondragon/tap-pocket"
repository = "https://github.com/edgarrmondragon/tap-pocket"
documentation = "https://github.com/edgarrmondragon/tap-pocket#readme"

[tool.poetry.dependencies]
python = "<3.11,>=3.7.1"
singer-sdk = "==0.4.4"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
black = "^22.3"
mypy = "^0.942"
types-requests = "^2.27.15"
isort = "^5.10.1"

# Flake8
flake8 = "^4.0.1"
flake8-docstrings = "^1.6.0"
flake8-annotations = "^2.7.0"
darglint = "^1.8.1"

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
src_paths = "tap_pocket"

[tool.pytest.ini_options]
addopts = "-vvv"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-pocket = 'tap_pocket.tap:TapPocket.cli'
