[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core==1.6.1",
]

[tool.poetry]
name = "tap-getpocket"
version = "0.0.1"
description = "`tap-getpocket` is a Singer tap for Pocket, built with the Meltano SDK for Singer Taps."
authors = ["Edgar Ramírez-Mondragón <edgarrm358@gmail.com>"]
keywords = ["ELT", "Pocket", "getpocket"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/edgarrmondragon/tap-getpocket"
repository = "https://github.com/edgarrmondragon/tap-getpocket"
documentation = "https://github.com/edgarrmondragon/tap-getpocket#readme"

[tool.poetry.dependencies]
python = "<3.12,>=3.7.1"
singer-sdk = "~=0.32.0"

[tool.poetry.dev-dependencies]
singer-sdk = { version = "*", extras = ["testing"] }

[tool.poetry.scripts]
# CLI declaration
tap-getpocket = 'tap_getpocket.tap:TapPocket.cli'

[tool.ruff]
ignore = [
    "ANN101", # missing-type-self
    "DJ",     # flake8-django
]
line-length = 88
select = ["ALL"]
target-version = "py37"
unfixable = [
  "ERA001",  # commented-out-code
]

[tool.ruff.per-file-ignores]
"tests/*" = ["ANN"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.isort]
profile = "black"
multi_line_output = 3       # Vertical Hanging Indent
src_paths = "tap_getpocket"

[tool.pytest.ini_options]
addopts = "-vvv"
